PRIV_DIR = $(MIX_APP_PATH)/priv
EX_DTLS_NIF_SO = $(PRIV_DIR)/libdtls.dll

!IF "$(OPENSSL_DIR)" == ""
OPENSSL_DIR = "C:/Program Files/OpenSSL"
!ENDIF

OPENSSL_INCLUDE_DIR = $(OPENSSL_DIR)/include
OPENSSL_LIB_DIR = $(OPENSSL_DIR)/lib

C_SRC = $(MAKEDIR)/c_src/ex_dtls
LIB_SRC = $(MAKEDIR)/lib
CFLAGS = /I"$(ERTS_INCLUDE_DIR)" /I"$(OPENSSL_INCLUDE_DIR)"
LFLAGS = /link "/libpath:$(OPENSSL_LIB_DIR)" libssl.lib libcrypto.lib
SOURCES = $(C_SRC)/native.c $(C_SRC)/dyn_buff.c $(C_SRC)/dtls.c $(C_SRC)/bio_frag.c

build: $(EX_DTLS_NIF_SO)

$(EX_DTLS_NIF_SO): $(SOURCES)
	@ if not exist "$(PRIV_DIR)" mkdir "$(PRIV_DIR)"
	$(CC) $(CFLAGS) /LD /MD /Fe$@ $(SOURCES) $(LFLAGS)

.PHONY: all